import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  grid: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
  },
  gradiente: {
    borderRadius: 20,
    borderColor: "red",
    borderWidth: 1,
    margin: 2,
    width: 80,
    height: 80,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },

  botonTexto: {
    color: "white",
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
  },
  contentValid: {
    borderColor: "grey",
    borderWidth: 4,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  textInput: {
    backgroundColor: "white",
    flex: 5,
    paddingLeft: 20,
    fontSize: 30,
    margin: 4,
    color: "lime",
    width: 300,
    height: 60,
  },
  textValid: {
    flex: 2,
    textAlign: "center",
    alignSelf: "center",
    backgroundColor: "white",
    color: "lime",
    fontSize: 20,
    fontWeight: "bold",
  },
  clear: {
    marginBottom: 50,
    marginRight: -60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  icon: {
    color: "white",
    backgroundColor: "grey",
    fontSize: 30,
    alignSelf: "center",
    marginLeft: 6,
    borderRadius: 100,
  },
  contentClear: {
    height: 200,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
});
